// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddReview(ctx context.Context, arg AddReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRestaurantCuisines(ctx context.Context, arg GetRestaurantCuisinesParams) ([]*string, error)
	GetRestaurants(ctx context.Context, arg GetRestaurantsParams) ([]GetRestaurantsRow, error)
	GetRestaurantsByFilter(ctx context.Context, arg GetRestaurantsByFilterParams) ([]GetRestaurantsByFilterRow, error)
	GetReviews(ctx context.Context, resID int32) ([]GetReviewsRow, error)
	GetUser(ctx context.Context, username *string) (User, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
